# Generated by Django 4.2.4 on 2023-08-26 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_about_category_about_contacts_about_rewards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='category',
        ),
        migrations.RemoveField(
            model_name='about',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='about',
            name='rewards',
        ),
    ]
