# Generated by Django 4.2.4 on 2023-08-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_about_category_remove_about_contacts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='page',
            field=models.CharField(choices=[('About', 'ABOUT')], max_length=30, null=True, verbose_name='Страница'),
        ),
    ]
