# Generated by Django 4.2.4 on 2023-08-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_about_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='page',
            field=models.CharField(choices=[('About', 'About'), ('Doctors', 'Doctors'), ('Services', 'Services'), ('Categories', 'Categories')], max_length=30, null=True, verbose_name='Страница'),
        ),
    ]
