# Generated by Django 4.2.4 on 2023-08-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='page',
            field=models.CharField(choices=[('about', 'About'), ('doctors', 'Doctors'), ('services', 'Services'), ('categories', 'cateogories'), ('index', 'index')], max_length=30, null=True, verbose_name='Страница'),
        ),
    ]
