# Generated by Django 4.2.4 on 2023-09-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='page',
            field=models.CharField(choices=[('about', 'About'), ('doctors', 'Doctors'), ('services', 'Services'), ('categories', 'cateogories'), ('index', 'index'), ('faq', 'faq')], max_length=30, null=True, verbose_name='Страница'),
        ),
    ]
