# Generated by Django 4.2.4 on 2023-08-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.TextField(blank=True, null=True, verbose_name='Опыт работы'),
        ),
    ]
