# Generated by Django 4.2.4 on 2023-08-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_about_page'),
        ('account', '0003_alter_doctor_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='category',
            field=models.ManyToManyField(related_name='doctors', to='post.category'),
        ),
    ]
