# Generated by Django 4.2.4 on 2023-09-14 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_appointment_medical_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='medical_history',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='uploaded_file',
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='medical_records/')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.appointment')),
            ],
            options={
                'verbose_name': 'Медицинская запись',
                'verbose_name_plural': 'Медицинские записи',
            },
        ),
    ]
